### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hipsterusername** [xinsir6/ControlNetPlus#4]
Hey Xinsir -

Great work again. We'll be looking at incorporating your work into Invoke's OSS studio soon. :)

Can you confirm that the code is also Apache 2, and update the GH repo with that license if so? We make all of our code Apache 2.0 so have to make sure we don't include anything in the code that wouldn't be compatible with that.

Appreciate your work - Let me know if you have any interest in the OMI or supporting your work.

**Comment by xinsir6** [comment]
OK, I will update the license soon. Any questions you can send to my email ddxin521@gmail.com

**Comment by xinsir6** [comment]
LICENSE have beed updated, you can use it as you like.
